version: 2
project_name: nfpm-helper
before:
  hooks:
    - go mod download
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ if index .Env "VERSION" }}{{ .Env.VERSION }}{{ else }}{{ .Version }}{{ end }}
archives:
  - formats:
      - zip
checksum:
  name_template: 'checksums.txt'
changelog:
  disable: true
release:
  disable: false
